### ISSUE TITLE
what‘s the data were used in this report? 

### ISSUE THREAD

**Issue by zhangabner** [Sharad24/Epileptic-Seizure-Detection#1]
I only find bellowing
https://www.isip.piconepress.com/projects/tuh_eeg/downloads/tuh_eeg_abnormal/v2.0.0/

and ChronoNet.ipynb is only a part of code? I can't find the code load the data and load the label.

could you provide a whole demo?

**Comment by Sharad24** [comment]
I've updated the code for loading the dataset. It's in the dataset class. I will provide a whole demo soon

**Comment by Athar-hussain** [comment]
it's been  ayear now ?

can know where you did it?

**Comment by Sharad24** [comment]
Hi @Athar-hussain 

I'm having a hard time finding time to take out for this. Most of the things are self-explanatory. Data Loading is the typical variable length data loading in pytorch. Plus from what I remember only the first 60 seconds were taken as mentioned in the ChronoNet paper.

**Comment by whubaichuan** [comment]
> I've updated the code for loading the dataset. It's in the dataset class. I will provide a whole demo soon

it seems you don't update.
